### PR TITLE
Fix carrierwave deps & output

### LINKED ISSUE #287: migrator logging should use mutex
otherwise it just writes all over itself.

### PR DESCRIPTION
**Pull request by zenspider**
This fixes #287 and #286.

### CODE REVIEW

File: lib/cloudinary/migrator.rb [hunk 1]
```diff
@@ -299,7 +299,9 @@ def start
   
   def debug(message)
     if @debug
-      $stderr.print "#{Time.now} Cloudinary::Migrator #{message}\n"
+      mutex.synchronize{
```
Comment (tocker) [inline lib/cloudinary/migrator.rb]: New line flushes the io stream, so this seems redundant (although not much harmful).
Please refer to my comment in the related issue.

File: vendor/assets/html/cloudinary_cors.html [hunk 2]
```diff
@@ -0,0 +1,43 @@
+<!DOCTYPE HTML>
```
Comment (tocker) [inline vendor/assets/html/cloudinary_cors.html]: We prefer not to include the bundled resources in the git repository.
However I will add instructions to fetch them when using the source code.

This folder should be removed before the PR can be merged.

File: lib/cloudinary/migrator.rb [hunk 3]
```diff
@@ -248,7 +248,7 @@ def start
               if defined?(ActiveRecord::Base) && data.is_a?(ActiveRecord::Base)
                 cw = true
                 data.save!
-              elsif defined?(Cloudinary::CarrierWave) && data.is_a?(Cloudinary::CarrierWave)
+              elsif defined?(::CarrierWave) && defined?(Cloudinary::CarrierWave) && data.is_a?(Cloudinary::CarrierWave)
```
Comment (tocker) [inline lib/cloudinary/migrator.rb]: Good catch!

File: lib/cloudinary/carrier_wave.rb [hunk 4]
```diff
@@ -3,7 +3,7 @@
 require 'cloudinary/carrier_wave/error'
 require 'cloudinary/carrier_wave/remote'
 require 'cloudinary/carrier_wave/preloaded'
-require 'cloudinary/carrier_wave/storage'
+require 'cloudinary/carrier_wave/storage' if defined?(::CarrierWave) # HACK
```
[the remark this answers is not in the document]
Comment (zenspider) [reply lib/cloudinary/carrier_wave.rb]: No, that's wrong. Requiring storage refers to `::CarrierWave` and causes this entire problem. It MUST not be required if carrierwave isn't being used.

File: vendor/assets/html/cloudinary_cors.html (hunk 2 above)
Comment (zenspider) [reply vendor/assets/html/cloudinary_cors.html]: I'm happy to remove this. I only did it because your code doesn't work as a `github:` bundled dependency without it. I should have put this on a separate branch so it didn't infect this PR.

**Comment by zenspider** [comment]
Removed the static assets.

Looks like your CI fails for other reasons not pertaining to this PR...

**Comment by tocker** [comment]
CI fails for all external PRs. It's a know issue: TravisCI doesn't pass secure environment variables to external PRs.
We're working on a solution.
